@Library('clouddevops-shared-library') _

pipeline {
    agent any

    environment {
        IMAGE_NAME = "clouddevops-app"
        ECR_URL    = "108782058667.dkr.ecr.us-east-1.amazonaws.com"
        AWS_REGION = "us-east-1"
        REPO_URL   = "https://github.com/lotfi029/CloudDevOpsProject.git"
        GIT_BRANCH = "main"
        IMAGE_TAG  = "${BUILD_NUMBER}"
    }

    stages {
        stage('Check Commit') {
            steps {
                script {
                    def commitAuthor = sh(
                        script: "git log -1 --pretty=format:'%an'",
                        returnStdout: true
                    ).trim()

                    def commitMsg = sh(
                        script: "git log -1 --pretty=%B",
                        returnStdout: true
                    ).trim()

                    echo "Commit author: ${commitAuthor}"
                    echo "Commit message: ${commitMsg}"

                    if (commitAuthor == "Jenkins CI" || commitMsg.contains('[skip ci]')) {
                        echo "Skipping pipeline — triggered by Jenkins CI commit."
                        currentBuild.result = 'NOT_BUILT'
                        return
                    }
                }
            }
        }

        stage('Build Image') {
            when {
                expression {
                    return currentBuild.result != 'NOT_BUILT'
                }
            }
            steps {
                script { buildImage(env.IMAGE_NAME, env.IMAGE_TAG) }
            }
        }

        stage('Scan Image') {
            when {
                expression { return currentBuild.result != 'NOT_BUILT' }
            }
            steps {
                script { scanImage(env.IMAGE_NAME, env.IMAGE_TAG) }
            }
        }

        stage('Push Image') {
            when {
                expression { return currentBuild.result != 'NOT_BUILT' }
            }
            steps {
                script { pushImage(env.ECR_URL, env.IMAGE_NAME, env.IMAGE_TAG, env.AWS_REGION) }
            }
        }

        stage('Delete Image Locally') {
            when {
                expression { return currentBuild.result != 'NOT_BUILT' }
            }
            steps {
                script { deleteLocalImage(env.IMAGE_NAME, env.IMAGE_TAG, env.ECR_URL) }
            }
        }

        stage('Update Manifests') {
            when {
                expression { return currentBuild.result != 'NOT_BUILT' }
            }
            steps {
                script { updateManifests(env.IMAGE_NAME, env.IMAGE_TAG, env.ECR_URL) }
            }
        }

        stage('Push Manifests') {
            when {
                expression { return currentBuild.result != 'NOT_BUILT' }
            }
            steps {
                script { pushManifests(env.REPO_URL, env.GIT_BRANCH, env.IMAGE_TAG) }
            }
        }
    }

    post {
        always { cleanWs() }
    }
}