apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ivolve-app-ingress
  namespace: ivolve
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: a003b45b6f46f4faebe59ef344206b1c-fc4fbd4976084767.elb.us-east-1.amazonaws.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ivolve-app-service
                port:
                  number: 80